/**
 * AEM Content Package Generator
 * Creates deployable .zip content packages for AEM Package Manager
 */

import JSZip from 'jszip';
import { ContentSuggestion } from './types.js';
import { contentToJcr } from './aem-content-structure.js';

export interface PackageConfig {
  name: string;
  group: string;
  version: string;
  description?: string;
  contentPath: string;
  buildCount?: number;
}

export interface PackageFilter {
  root: string;
  rules?: Array<{ modifier: 'include' | 'exclude'; pattern: string }>;
}

/**
 * Generate package properties XML
 */
function generatePropertiesXml(config: PackageConfig): string {
  const now = new Date();
  const timestamp = now.getTime();

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
  <comment>FileVault Package Properties</comment>
  <entry key="name">${config.name}</entry>
  <entry key="group">${config.group}</entry>
  <entry key="version">${config.version}</entry>
  <entry key="description">${config.description || 'Generated by AEM Component Factory'}</entry>
  <entry key="buildCount">${config.buildCount || 1}</entry>
  <entry key="created">${now.toISOString()}</entry>
  <entry key="createdBy">aem-component-factory</entry>
  <entry key="lastModified">${now.toISOString()}</entry>
  <entry key="lastModifiedBy">aem-component-factory</entry>
  <entry key="packageType">content</entry>
  <entry key="requiresRoot">false</entry>
</properties>`;
}

/**
 * Generate filter.xml for package
 */
function generateFilterXml(filters: PackageFilter[]): string {
  const filterEntries = filters.map(filter => {
    const rules = filter.rules?.map(rule =>
      `      <${rule.modifier} pattern="${rule.pattern}" />`
    ).join('\n') || '';

    return `    <filter root="${filter.root}">${rules ? '\n' + rules + '\n    ' : ''}</filter>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<workspaceFilter version="1.0">
${filterEntries}
</workspaceFilter>`;
}

/**
 * Generate .content.xml for JCR node
 */
function generateContentXml(jcrContent: Record<string, unknown>, indent = 0): string {
  const spaces = '  '.repeat(indent);
  const props: string[] = [];
  const children: string[] = [];

  for (const [key, value] of Object.entries(jcrContent)) {
    if (value === null || value === undefined) continue;

    if (typeof value === 'object' && !Array.isArray(value)) {
      // Child node
      const childXml = generateContentXml(value as Record<string, unknown>, indent + 1);
      children.push(`${spaces}  <${escapeXmlName(key)}${childXml.startsWith('\n') ? '' : ' '}${childXml}</${escapeXmlName(key)}>`);
    } else {
      // Property
      const propValue = formatXmlProperty(key, value);
      if (propValue) {
        props.push(propValue);
      }
    }
  }

  if (props.length === 0 && children.length === 0) {
    return '/>';
  }

  let result = '';
  if (props.length > 0) {
    result += '\n' + props.map(p => `${spaces}  ${p}`).join('\n');
  }

  if (children.length > 0) {
    result += '>\n' + children.join('\n') + '\n' + spaces;
  } else if (props.length > 0) {
    result += '>';
  }

  return result;
}

function escapeXmlName(name: string): string {
  // JCR names with colons need special handling
  return name.replace(/:/g, '_x003a_');
}

function formatXmlProperty(key: string, value: unknown): string | null {
  const xmlKey = key.replace(/:/g, ':');

  if (typeof value === 'string') {
    return `${xmlKey}="${escapeXmlValue(value)}"`;
  } else if (typeof value === 'boolean') {
    return `${xmlKey}="{Boolean}${value}"`;
  } else if (typeof value === 'number') {
    if (Number.isInteger(value)) {
      return `${xmlKey}="{Long}${value}"`;
    }
    return `${xmlKey}="{Double}${value}"`;
  } else if (Array.isArray(value)) {
    const items = value.map(v => escapeXmlValue(String(v))).join(',');
    return `${xmlKey}="[${items}]"`;
  }

  return null;
}

function escapeXmlValue(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Generate a full .content.xml file
 */
function generateFullContentXml(jcrContent: Record<string, unknown>): string {
  const rootProps = generateContentXml(jcrContent);

  return `<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:jcr="http://www.jcp.org/jcr/1.0"
          xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
          xmlns:cq="http://www.day.com/jcr/cq/1.0"
          xmlns:sling="http://sling.apache.org/jcr/sling/1.0"${rootProps}
</jcr:root>`;
}

/**
 * Create content package from content suggestions
 */
export async function createContentPackage(
  contents: ContentSuggestion[],
  config: PackageConfig
): Promise<Blob> {
  const zip = new JSZip();

  // Create META-INF structure
  const metaInf = zip.folder('META-INF');
  const vault = metaInf!.folder('vault');

  // Add properties.xml
  vault!.file('properties.xml', generatePropertiesXml(config));

  // Create filters for content
  const filters: PackageFilter[] = [{
    root: config.contentPath,
    rules: [{ modifier: 'include', pattern: `${config.contentPath}/.*` }]
  }];
  vault!.file('filter.xml', generateFilterXml(filters));

  // Add config.xml
  vault!.file('config.xml', `<?xml version="1.0" encoding="UTF-8"?>
<vaultfs version="1.1">
  <aggregates>
    <aggregate name="page" primaryType="cq:Page"/>
    <aggregate name="component" primaryType="cq:Component"/>
  </aggregates>
</vaultfs>`);

  // Add definition/.content.xml
  const definition = vault!.folder('definition');
  definition!.file('.content.xml', `<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:jcr="http://www.jcp.org/jcr/1.0"
          xmlns:vlt="http://www.day.com/jcr/vault/1.0"
          jcr:primaryType="vlt:PackageDefinition"
          name="${config.name}"
          group="${config.group}"
          version="${config.version}"/>`);

  // Create jcr_root structure
  const jcrRoot = zip.folder('jcr_root');

  // Add content for each suggestion
  for (let i = 0; i < contents.length; i++) {
    const content = contents[i];
    const jcrContent = contentToJcr(content, {
      path: `${config.contentPath}/component-${i + 1}`,
      resourceType: `aem-component-factory/components/${content.componentType || 'teaser'}`
    });

    // Create folder structure
    const pathParts = config.contentPath.split('/').filter(p => p);
    let currentFolder = jcrRoot;

    for (const part of pathParts) {
      currentFolder = currentFolder!.folder(part)!;
    }

    // Add component folder
    const componentFolder = currentFolder!.folder(`component-${i + 1}`);
    componentFolder!.file('.content.xml', generateFullContentXml(jcrContent));
  }

  // Generate zip blob
  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });
}

/**
 * Create page content package
 */
export async function createPagePackage(
  contents: ContentSuggestion[],
  pageConfig: {
    pagePath: string;
    pageTitle: string;
    template: string;
  },
  packageConfig: PackageConfig
): Promise<Blob> {
  const zip = new JSZip();

  // Create META-INF structure
  const metaInf = zip.folder('META-INF');
  const vault = metaInf!.folder('vault');

  vault!.file('properties.xml', generatePropertiesXml(packageConfig));

  const filters: PackageFilter[] = [{
    root: pageConfig.pagePath,
  }];
  vault!.file('filter.xml', generateFilterXml(filters));

  // Create jcr_root with page structure
  const jcrRoot = zip.folder('jcr_root');
  const pathParts = pageConfig.pagePath.split('/').filter(p => p);

  let currentFolder = jcrRoot;
  for (const part of pathParts) {
    currentFolder = currentFolder!.folder(part)!;
  }

  // Create page .content.xml
  const pageJcr: Record<string, unknown> = {
    'jcr:primaryType': 'cq:Page',
    'jcr:content': {
      'jcr:primaryType': 'cq:PageContent',
      'jcr:title': pageConfig.pageTitle,
      'sling:resourceType': pageConfig.template,
      'cq:template': `/conf/aem-component-factory/settings/wcm/templates/${pageConfig.template.split('/').pop()}`,
    }
  };

  // Add components to page
  const jcrContent = pageJcr['jcr:content'] as Record<string, unknown>;
  const root = { 'jcr:primaryType': 'nt:unstructured', 'sling:resourceType': 'wcm/foundation/components/responsivegrid' } as Record<string, unknown>;

  contents.forEach((content, index) => {
    root[`component_${index}`] = contentToJcr(content, {
      path: `${pageConfig.pagePath}/jcr:content/root/component_${index}`,
      resourceType: `core/wcm/components/${content.componentType || 'teaser'}/v2/${content.componentType || 'teaser'}`
    });
  });

  jcrContent['root'] = root;

  currentFolder!.file('.content.xml', generateFullContentXml(pageJcr));

  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });
}

/**
 * Download package as file
 */
export function downloadPackage(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
