extensions:
  - extension_point_id: dx/excshell/1
    id: aem-a2ui-actions
    runtime:
      actions:
        generate:
          function: actions/generate/index.js
          web: raw
          annotations:
            require-adobe-auth: true
            final: true
          inputs:
            AI_AGENT_URL: $AI_AGENT_URL
          outputs:
            statusCode: 200
            body: {}
        suggest:
          function: actions/suggest/index.js
          web: raw
          annotations:
            require-adobe-auth: true
            final: true
          inputs:
            AI_AGENT_URL: $AI_AGENT_URL
